In [1]:
import numpy as np

In [2]:
 l = ["abc", 23,8,7,6,5]

In [3]:
type(l)

list

In [5]:
type(np.array(l))

numpy.ndarray

In [12]:
a1=np.array([4,56,5,6,3.4,5])

In [8]:
a = np.array([[1,3],[2,4]])

In [9]:
a

array([[1, 3],
       [2, 4]])

In [10]:
a[1][1]

4

In [11]:
a[1][0]

2

In [13]:
a1[0]

4.0

In [15]:
a1[4]

3.4

In [16]:
type(a1)

numpy.ndarray

In [26]:
np.array([1,2,3,4], ndmin=1)

array([1, 2, 3, 4])

In [27]:
np.array([1,2,3,4], ndmin=2)

array([[1, 2, 3, 4]])

In [29]:
x = np.array([1,2,3,4], ndmin=3)

In [34]:
x[0][0][3]

4

In [50]:
a = [2,6,4,5,8]
np.asarray([2,6,4,5,8])

array([2, 6, 4, 5, 8])

In [42]:
np.asanyarray([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [2]:
np.mat([1,2,3,4,5])

matrix([[1, 2, 3, 4, 5]])

In [51]:
np.asanyarray(np.mat(a))

matrix([[2, 6, 4, 5, 8]])

In [58]:
np.fromfunction(lambda i,j : i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [66]:
np.fromfunction(lambda i, j: i*j, (4,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [67]:
np.fromfunction(lambda i, j, k: i*j*k, (4,4,4),dtype=int)

array([[[ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 0,  0,  0,  0],
        [ 0,  1,  2,  3],
        [ 0,  2,  4,  6],
        [ 0,  3,  6,  9]],

       [[ 0,  0,  0,  0],
        [ 0,  2,  4,  6],
        [ 0,  4,  8, 12],
        [ 0,  6, 12, 18]],

       [[ 0,  0,  0,  0],
        [ 0,  3,  6,  9],
        [ 0,  6, 12, 18],
        [ 0,  9, 18, 27]]])

In [3]:
np.fromfunction(lambda i, j, k: i+j+k, (4,4,2),dtype=int)

array([[[0, 1],
        [1, 2],
        [2, 3],
        [3, 4]],

       [[1, 2],
        [2, 3],
        [3, 4],
        [4, 5]],

       [[2, 3],
        [3, 4],
        [4, 5],
        [5, 6]],

       [[3, 4],
        [4, 5],
        [5, 6],
        [6, 7]]])

In [71]:
np.mat(np.fromfunction(lambda i, j, k: i*j*k, (4,4,4),dtype=int))

ValueError: shape too large to be a matrix.

In [73]:
np.mat(np.fromfunction(lambda i, j: i*j, (4,4),dtype=int))

matrix([[0, 0, 0, 0],
        [0, 1, 2, 3],
        [0, 2, 4, 6],
        [0, 3, 6, 9]])

In [4]:
a = np.fromfunction(lambda i, j, k, l: i+j+k+l, (3, 4, 3, 2),dtype=int)

In [110]:
a.reshape(9,8)

array([[0, 1, 1, 2, 2, 3, 1, 2],
       [2, 3, 3, 4, 2, 3, 3, 4],
       [4, 5, 3, 4, 4, 5, 5, 6],
       [1, 2, 2, 3, 3, 4, 2, 3],
       [3, 4, 4, 5, 3, 4, 4, 5],
       [5, 6, 4, 5, 5, 6, 6, 7],
       [2, 3, 3, 4, 4, 5, 3, 4],
       [4, 5, 5, 6, 4, 5, 5, 6],
       [6, 7, 5, 6, 6, 7, 7, 8]])

In [111]:
a.reshape(6,6,2)

array([[[0, 1],
        [1, 2],
        [2, 3],
        [1, 2],
        [2, 3],
        [3, 4]],

       [[2, 3],
        [3, 4],
        [4, 5],
        [3, 4],
        [4, 5],
        [5, 6]],

       [[1, 2],
        [2, 3],
        [3, 4],
        [2, 3],
        [3, 4],
        [4, 5]],

       [[3, 4],
        [4, 5],
        [5, 6],
        [4, 5],
        [5, 6],
        [6, 7]],

       [[2, 3],
        [3, 4],
        [4, 5],
        [3, 4],
        [4, 5],
        [5, 6]],

       [[4, 5],
        [5, 6],
        [6, 7],
        [5, 6],
        [6, 7],
        [7, 8]]])

In [112]:
a.reshape(6,12)

array([[0, 1, 1, 2, 2, 3, 1, 2, 2, 3, 3, 4],
       [2, 3, 3, 4, 4, 5, 3, 4, 4, 5, 5, 6],
       [1, 2, 2, 3, 3, 4, 2, 3, 3, 4, 4, 5],
       [3, 4, 4, 5, 5, 6, 4, 5, 5, 6, 6, 7],
       [2, 3, 3, 4, 4, 5, 3, 4, 4, 5, 5, 6],
       [4, 5, 5, 6, 6, 7, 5, 6, 6, 7, 7, 8]])

In [117]:
a.reshape(6,6,1,2)

array([[[[0, 1]],

        [[1, 2]],

        [[2, 3]],

        [[1, 2]],

        [[2, 3]],

        [[3, 4]]],


       [[[2, 3]],

        [[3, 4]],

        [[4, 5]],

        [[3, 4]],

        [[4, 5]],

        [[5, 6]]],


       [[[1, 2]],

        [[2, 3]],

        [[3, 4]],

        [[2, 3]],

        [[3, 4]],

        [[4, 5]]],


       [[[3, 4]],

        [[4, 5]],

        [[5, 6]],

        [[4, 5]],

        [[5, 6]],

        [[6, 7]]],


       [[[2, 3]],

        [[3, 4]],

        [[4, 5]],

        [[3, 4]],

        [[4, 5]],

        [[5, 6]]],


       [[[4, 5]],

        [[5, 6]],

        [[6, 7]],

        [[5, 6]],

        [[6, 7]],

        [[7, 8]]]])

In [120]:
a.reshape(2,2,-1)

array([[[0, 1, 1, 2, 2, 3, 1, 2, 2, 3, 3, 4, 2, 3, 3, 4, 4, 5],
        [3, 4, 4, 5, 5, 6, 1, 2, 2, 3, 3, 4, 2, 3, 3, 4, 4, 5]],

       [[3, 4, 4, 5, 5, 6, 4, 5, 5, 6, 6, 7, 2, 3, 3, 4, 4, 5],
        [3, 4, 4, 5, 5, 6, 4, 5, 5, 6, 6, 7, 5, 6, 6, 7, 7, 8]]])

In [87]:
a.ndim

4

In [88]:
a.size

72

In [89]:
a.shape

(3, 4, 3, 2)

In [90]:
a.dtype

dtype('int32')

In [91]:
a = np.fromfunction(lambda i, j: i*j, (4,4),dtype=int)

In [92]:
a

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [94]:
import pandas as pd
pd.DataFrame(a)

0  1  2  3
0  0  0  0  0
1  0  1  2  3
2  0  2  4  6
3  0  3  6  9

In [95]:
a = np.fromfunction(lambda i, j: i*j, (50,63),dtype=int)

In [96]:
pd.DataFrame(a)

0   1   2    3    4    5    6    7    8    9   ...    53    54    55  \
0    0   0   0    0    0    0    0    0    0    0  ...     0     0     0   
1    0   1   2    3    4    5    6    7    8    9  ...    53    54    55   
2    0   2   4    6    8   10   12   14   16   18  ...   106   108   110   
3    0   3   6    9   12   15   18   21   24   27  ...   159   162   165   
4    0   4   8   12   16   20   24   28   32   36  ...   212   216   220   
5    0   5  10   15   20   25   30   35   40   45  ...   265   270   275   
6    0   6  12   18   24   30   36   42   48   54  ...   318   324   330   
7    0   7  14   21   28   35   42   49   56   63  ...   371   378   385   
8    0   8  16   24   32   40   48   56   64   72  ...   424   432   440   
9    0   9  18   27   36   45   54   63   72   81  ...   477   486   495   
10   0  10  20   30   40   50   60   70   80   90  ...   530   540   550   
11   0  11  22   33   44   55   66   77   88   99  ...   583   594   605   
12   0  12  24   36   48   60   72   84   96  108  ...   636   648   660   
13   0  13  26   39   52   65   78   91  104  117  ...   689   702   715   
14   0  14  28   42   56   70   84   98  112  126  ...   742   756   770   
15   0  15  30   45   60   75   90  105  120  135  ...   795   810   825   
16   0  16  32   48   64   80   96  112  128  144  ...   848   864   880   
17   0  17  34   51   68   85  102  119  136  153  ...   901   918   935   
18   0  18  36   54   72   90  108  126  144  162  ...   954   972   990   
19   0  19  38   57   76   95  114  133  152  171  ...  1007  1026  1045   
20   0  20  40   60   80  100  120  140  160  180  ...  1060  1080  1100   
21   0  21  42   63   84  105  126  147  168  189  ...  1113  1134  1155   
22   0  22  44   66   88  110  132  154  176  198  ...  1166  1188  1210   
23   0  23  46   69   92  115  138  161  184  207  ...  1219  1242  1265   
24   0  24  48   72   96  120  144  168  192  216  ...  1272  1296  1320   
25   0  25  50   75  100  125  150  175  200  225  ...  1325  1350  1375   
26   0  26  52   78  104  130  156  182  208  234  ...  1378  1404  1430   
27   0  27  54   81  108  135  162  189  216  243  ...  1431  1458  1485   
28   0  28  56   84  112  140  168  196  224  252  ...  1484  1512  1540   
29   0  29  58   87  116  145  174  203  232  261  ...  1537  1566  1595   
30   0  30  60   90  120  150  180  210  240  270  ...  1590  1620  1650   
31   0  31  62   93  124  155  186  217  248  279  ...  1643  1674  1705   
32   0  32  64   96  128  160  192  224  256  288  ...  1696  1728  1760   
33   0  33  66   99  132  165  198  231  264  297  ...  1749  1782  1815   
34   0  34  68  102  136  170  204  238  272  306  ...  1802  1836  1870   
35   0  35  70  105  140  175  210  245  280  315  ...  1855  1890  1925   
36   0  36  72  108  144  180  216  252  288  324  ...  1908  1944  1980   
37   0  37  74  111  148  185  222  259  296  333  ...  1961  1998  2035   
38   0  38  76  114  152  190  228  266  304  342  ...  2014  2052  2090   
39   0  39  78  117  156  195  234  273  312  351  ...  2067  2106  2145   
40   0  40  80  120  160  200  240  280  320  360  ...  2120  2160  2200   
41   0  41  82  123  164  205  246  287  328  369  ...  2173  2214  2255   
42   0  42  84  126  168  210  252  294  336  378  ...  2226  2268  2310   
43   0  43  86  129  172  215  258  301  344  387  ...  2279  2322  2365   
44   0  44  88  132  176  220  264  308  352  396  ...  2332  2376  2420   
45   0  45  90  135  180  225  270  315  360  405  ...  2385  2430  2475   
46   0  46  92  138  184  230  276  322  368  414  ...  2438  2484  2530   
47   0  47  94  141  188  235  282  329  376  423  ...  2491  2538  2585   
48   0  48  96  144  192  240  288  336  384  432  ...  2544  2592  2640   
49   0  49  98  147  196  245  294  343  392  441  ...  2597  2646  2695   

      56    57    58    59    60    61    62  
0      0     0     0     0     0     0     0  
1     56    57    58    59    60 

In [6]:
np.random.rand(2, 3, 4)

array([[[0.85044411, 0.11583471, 0.74326298, 0.75558781],
        [0.44268781, 0.97914913, 0.97873456, 0.76570105],
        [0.81527623, 0.22854774, 0.22386392, 0.24392691]],

       [[0.59501997, 0.56660978, 0.44258261, 0.16931072],
        [0.14218603, 0.40286531, 0.16768956, 0.32341898],
        [0.6085324 , 0.48396341, 0.6254362 , 0.4193485 ]]])

In [104]:
np.random.randint(10,20)

12

In [106]:
np.random.randn(4,4)

array([[ 1.49641135, -0.11183883, -0.44082792, -0.19266789],
       [ 0.57949449,  0.17396266, -0.36922054, -0.96913993],
       [ 0.93994028, -0.9740126 ,  1.32258756, -0.63580842],
       [-1.74673448,  1.19073664,  1.56191645,  0.30980047]])

In [114]:
pd.DataFrame(a.reshape(9,8))

0  1  2  3  4  5  6  7
0  0  1  1  2  2  3  1  2
1  2  3  3  4  2  3  3  4
2  4  5  3  4  4  5  5  6
3  1  2  2  3  3  4  2  3
4  3  4  4  5  3  4  4  5
5  5  6  4  5  5  6  6  7
6  2  3  3  4  4  5  3  4
7  4  5  5  6  4  5  5  6
8  6  7  5  6  6  7  7  8

In [122]:
list(range(4,10))

[4, 5, 6, 7, 8, 9]

In [127]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [133]:
np.arange(2,10, 2)

array([2, 4, 6, 8])

In [164]:
arr = np.random.rand(10,8)

In [165]:
arr

array([[0.52537909, 0.42129797, 0.25050181, 0.11631013, 0.79989646,
        0.28833784, 0.91716542, 0.6087625 ],
       [0.37403341, 0.0534262 , 0.16646157, 0.05888736, 0.42568025,
        0.73660861, 0.98795017, 0.63256761],
       [0.90772467, 0.1163974 , 0.83149777, 0.29275711, 0.75602835,
        0.05771343, 0.92257052, 0.96811441],
       [0.11071673, 0.38013985, 0.13564122, 0.50814956, 0.09956132,
        0.5914429 , 0.99560365, 0.67867784],
       [0.06510859, 0.16365081, 0.79909302, 0.93962515, 0.10872363,
        0.97791203, 0.01214691, 0.45776771],
       [0.34024439, 0.93114336, 0.45017337, 0.19494103, 0.98032436,
        0.68771458, 0.93452393, 0.93024409],
       [0.98916947, 0.91796071, 0.36678542, 0.36168169, 0.16110473,
        0.51183823, 0.62752594, 0.94764316],
       [0.76300192, 0.99303265, 0.09464191, 0.56730582, 0.89250462,
        0.29120899, 0.65939718, 0.67110472],
       [0.23682927, 0.50996866, 0.81546987, 0.81384019, 0.03462937,
        0.16271212, 0.443973

In [166]:
arr[arr>.5]

array([0.52537909, 0.79989646, 0.91716542, 0.6087625 , 0.73660861,
       0.98795017, 0.63256761, 0.90772467, 0.83149777, 0.75602835,
       0.92257052, 0.96811441, 0.50814956, 0.5914429 , 0.99560365,
       0.67867784, 0.79909302, 0.93962515, 0.97791203, 0.93114336,
       0.98032436, 0.68771458, 0.93452393, 0.93024409, 0.98916947,
       0.91796071, 0.51183823, 0.62752594, 0.94764316, 0.76300192,
       0.99303265, 0.56730582, 0.89250462, 0.65939718, 0.67110472,
       0.50996866, 0.81546987, 0.81384019, 0.54199242, 0.7494727 ,
       0.93066922, 0.88977878, 0.5700673 , 0.65002901])

In [168]:
arr[[1,2],[2]]

array([0.16646157, 0.83149777])

In [170]:
a2=arr[3:8, 0:4]

In [171]:
a2

array([[0.11071673, 0.38013985, 0.13564122, 0.50814956],
       [0.06510859, 0.16365081, 0.79909302, 0.93962515],
       [0.34024439, 0.93114336, 0.45017337, 0.19494103],
       [0.98916947, 0.91796071, 0.36678542, 0.36168169],
       [0.76300192, 0.99303265, 0.09464191, 0.56730582]])

In [172]:
a2[0][0]

0.11071672683192746

In [173]:
a2[0][0]=0.324565

In [174]:
a2

array([[0.324565  , 0.38013985, 0.13564122, 0.50814956],
       [0.06510859, 0.16365081, 0.79909302, 0.93962515],
       [0.34024439, 0.93114336, 0.45017337, 0.19494103],
       [0.98916947, 0.91796071, 0.36678542, 0.36168169],
       [0.76300192, 0.99303265, 0.09464191, 0.56730582]])

In [179]:
a = np.array([[1,2],[3,4]])

In [188]:
b = np.array([[2,3],[4,5]])

In [181]:
a

array([[1, 2],
       [3, 4]])

In [182]:
b

array([[2, 3],
       [4, 5]])

In [189]:
a*b

array([[ 2,  6],
       [12, 20]])

In [191]:
m = a@b

In [196]:
m/0

C:\Users\bvams\AppData\Local\Temp\ipykernel_23612\3791875896.py:1: RuntimeWarning: divide by zero encountered in true_divide
  m/0


array([[inf, inf],
       [inf, inf]])