In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5,6]

In [3]:
np.asarray(l)

array([1, 2, 3, 4, 5, 6])

In [4]:
np.array(l, ndmin = 3)

array([[[1, 2, 3, 4, 5, 6]]])

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.ones((3,6,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [21]:
5+np.zeros(3)

array([5., 5., 5.])

In [20]:
5+np.zeros((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [23]:
5+np.zeros((6,3,4))

array([[[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]],

       [[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]],

       [[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]],

       [[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]],

       [[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]],

       [[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]]])

In [25]:
np.ones((3,4))+np.zeros((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
np.empty((5,5,2))

array([[[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 6.95167125e-310],
        [2.27270197e-322, 1.24095707e-311],
        [1.24095707e-311, 1.24095707e-311],
        [1.24095725e-311, 1.24095143e-311]],

       [[1.24095725e-311, 1.24095725e-311],
        [1.24095699e-311, 1.24095725e-311],
        [1.24095143e-311, 1.24095721e-311],
        [1.24095725e-311, 1.24095721e-311],
        [1.24095725e-311, 1.24095725e-311]],

       [[1.24095721e-311, 1.24095143e-311],
        [1.24095725e-311, 1.24095143e-311],
        [1.24095725e-311, 1.24095143e-311],
        [1.24095143e-311, 1.24095143e-311],
        [1.24095143e-311, 1.24095143e-311]],

       [[1.24095725e-311, 1.24095143e-311],
        [1.24095143e-311, 1.24095143e-311],
        [1.24095143e-311, 1.24095143e-311],
        [1.24095143e-311, 1.24095143e-311],
        [1.24095143e-311, 1.24095725e-311]],

       [[1.24095725e-311, 1.24095725e-311],
        [1.24095723e-311, 1.24095725e-311],
        [1.24095723e-311

In [36]:
np.empty((6,5,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [37]:
np.empty((2,5,2))

array([[[4.67296746e-307, 1.69121096e-306],
        [7.56605239e-307, 7.56587585e-307],
        [1.37961302e-306, 1.05699242e-307],
        [8.01097889e-307, 1.78020169e-306],
        [7.56601165e-307, 1.02359984e-306]],

       [[1.33510679e-306, 2.22522597e-306],
        [1.33511018e-306, 6.23057689e-307],
        [8.45597329e-307, 8.45559303e-307],
        [8.06613465e-308, 6.89810244e-307],
        [1.22387550e-307, 2.22522596e-306]]])

In [41]:
np.linspace(2,6)

array([2.        , 2.08163265, 2.16326531, 2.24489796, 2.32653061,
       2.40816327, 2.48979592, 2.57142857, 2.65306122, 2.73469388,
       2.81632653, 2.89795918, 2.97959184, 3.06122449, 3.14285714,
       3.2244898 , 3.30612245, 3.3877551 , 3.46938776, 3.55102041,
       3.63265306, 3.71428571, 3.79591837, 3.87755102, 3.95918367,
       4.04081633, 4.12244898, 4.20408163, 4.28571429, 4.36734694,
       4.44897959, 4.53061224, 4.6122449 , 4.69387755, 4.7755102 ,
       4.85714286, 4.93877551, 5.02040816, 5.10204082, 5.18367347,
       5.26530612, 5.34693878, 5.42857143, 5.51020408, 5.59183673,
       5.67346939, 5.75510204, 5.83673469, 5.91836735, 6.        ])

In [42]:
np.linspace(2,6,20)

array([2.        , 2.21052632, 2.42105263, 2.63157895, 2.84210526,
       3.05263158, 3.26315789, 3.47368421, 3.68421053, 3.89473684,
       4.10526316, 4.31578947, 4.52631579, 4.73684211, 4.94736842,
       5.15789474, 5.36842105, 5.57894737, 5.78947368, 6.        ])

In [43]:
np.linspace(2,6,1000)

array([2.        , 2.004004  , 2.00800801, 2.01201201, 2.01601602,
       2.02002002, 2.02402402, 2.02802803, 2.03203203, 2.03603604,
       2.04004004, 2.04404404, 2.04804805, 2.05205205, 2.05605606,
       2.06006006, 2.06406406, 2.06806807, 2.07207207, 2.07607608,
       2.08008008, 2.08408408, 2.08808809, 2.09209209, 2.0960961 ,
       2.1001001 , 2.1041041 , 2.10810811, 2.11211211, 2.11611612,
       2.12012012, 2.12412412, 2.12812813, 2.13213213, 2.13613614,
       2.14014014, 2.14414414, 2.14814815, 2.15215215, 2.15615616,
       2.16016016, 2.16416416, 2.16816817, 2.17217217, 2.17617618,
       2.18018018, 2.18418418, 2.18818819, 2.19219219, 2.1961962 ,
       2.2002002 , 2.2042042 , 2.20820821, 2.21221221, 2.21621622,
       2.22022022, 2.22422422, 2.22822823, 2.23223223, 2.23623624,
       2.24024024, 2.24424424, 2.24824825, 2.25225225, 2.25625626,
       2.26026026, 2.26426426, 2.26826827, 2.27227227, 2.27627628,
       2.28028028, 2.28428428, 2.28828829, 2.29229229, 2.29629

In [50]:
np.linspace(2,6,1500)

array([2.        , 2.00266845, 2.00533689, ..., 5.99466311, 5.99733155,
       6.        ])

In [51]:
np.linspace(2,6,10)

array([2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778,
       4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ])

In [52]:
np.array(np.linspace(2,6,20),ndmin=3)

array([[[2.        , 2.21052632, 2.42105263, 2.63157895, 2.84210526,
         3.05263158, 3.26315789, 3.47368421, 3.68421053, 3.89473684,
         4.10526316, 4.31578947, 4.52631579, 4.73684211, 4.94736842,
         5.15789474, 5.36842105, 5.57894737, 5.78947368, 6.        ]]])

In [54]:
np.linspace(2,6,20).reshape(4,5)

array([[2.        , 2.21052632, 2.42105263, 2.63157895, 2.84210526],
       [3.05263158, 3.26315789, 3.47368421, 3.68421053, 3.89473684],
       [4.10526316, 4.31578947, 4.52631579, 4.73684211, 4.94736842],
       [5.15789474, 5.36842105, 5.57894737, 5.78947368, 6.        ]])

In [55]:
np.linspace(2,6,20, endpoint=False).reshape(4,5)

array([[2. , 2.2, 2.4, 2.6, 2.8],
       [3. , 3.2, 3.4, 3.6, 3.8],
       [4. , 4.2, 4.4, 4.6, 4.8],
       [5. , 5.2, 5.4, 5.6, 5.8]])

In [57]:
np.linspace(2,6,10).reshape(5,2)

array([[2.        , 2.44444444],
       [2.88888889, 3.33333333],
       [3.77777778, 4.22222222],
       [4.66666667, 5.11111111],
       [5.55555556, 6.        ]])

In [58]:
np.linspace(2,6,20, endpoint = False).reshape(5,4)

array([[2. , 2.2, 2.4, 2.6],
       [2.8, 3. , 3.2, 3.4],
       [3.6, 3.8, 4. , 4.2],
       [4.4, 4.6, 4.8, 5. ],
       [5.2, 5.4, 5.6, 5.8]])

In [61]:
x=np.linspace(2,6,20, endpoint = False, retstep=True)

In [69]:
np.logspace(2,4,10, base = 10)

array([  100.        ,   166.81005372,   278.25594022,   464.15888336,
         774.26368268,  1291.54966501,  2154.43469003,  3593.8136638 ,
        5994.84250319, 10000.        ])

In [70]:
np.logspace(2,4,10, base = 2)

array([ 4.        ,  4.66611616,  5.44316   ,  6.34960421,  7.4069977 ,
        8.64047791, 10.0793684 , 11.75787594, 13.71590373, 16.        ])

In [71]:
np.logspace(2,2,1, base = 10)

array([100.])

In [5]:
np.logspace(3,6)

array([   1000.        ,    1151.39539933,    1325.71136559,
          1526.41796718,    1757.51062485,    2023.58964773,
          2329.95181052,    2682.69579528,    3088.84359648,
          3556.48030622,    4094.91506238,    4714.86636346,
          5428.67543932,    6250.55192527,    7196.85673001,
          8286.42772855,    9540.9547635 ,   10985.41141988,
         12648.55216855,   14563.48477501,   16768.32936811,
         19306.97728883,   22229.96482526,   25595.479227  ,
         29470.51702552,   33932.21771895,   39069.39937055,
         44984.32668969,   51794.74679231,   59636.23316595,
         68664.88450043,   79060.43210908,   91029.81779915,
        104811.31341547,  120679.26406393,  138949.54943731,
        159985.87196061,  184206.99693267,  212095.08879202,
        244205.30945486,  281176.86979742,  323745.75428176,
        372759.37203149,  429193.42601288,  494171.33613238,
        568986.60290183,  655128.55685955,  754312.00633546,
        868511.37375135,

In [2]:
np.linspace(2, 4)

array([2.        , 2.04081633, 2.08163265, 2.12244898, 2.16326531,
       2.20408163, 2.24489796, 2.28571429, 2.32653061, 2.36734694,
       2.40816327, 2.44897959, 2.48979592, 2.53061224, 2.57142857,
       2.6122449 , 2.65306122, 2.69387755, 2.73469388, 2.7755102 ,
       2.81632653, 2.85714286, 2.89795918, 2.93877551, 2.97959184,
       3.02040816, 3.06122449, 3.10204082, 3.14285714, 3.18367347,
       3.2244898 , 3.26530612, 3.30612245, 3.34693878, 3.3877551 ,
       3.42857143, 3.46938776, 3.51020408, 3.55102041, 3.59183673,
       3.63265306, 3.67346939, 3.71428571, 3.75510204, 3.79591837,
       3.83673469, 3.87755102, 3.91836735, 3.95918367, 4.        ])

In [79]:
a = np.arange(16).reshape(4,4)

In [80]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [81]:
a.max()

15

In [82]:
a.min()

0

In [84]:
a[2][2]

10

In [85]:
a = np.arange(4,40).reshape(3,6,2)

In [86]:
a

array([[[ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27]],

       [[28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

In [88]:
a.max()

39

In [97]:
a.max(axis=1)

array([[14, 15],
       [26, 27],
       [38, 39]])

In [98]:
a = np.arange(4,40).reshape(6,6)

In [99]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [100]:
a.max(axis=0)

array([34, 35, 36, 37, 38, 39])

In [101]:
a.max(axis =1)

array([ 9, 15, 21, 27, 33, 39])

In [102]:
10 + a

array([[14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49]])

In [105]:
a/0

C:\Users\bvams\AppData\Local\Temp\ipykernel_19836\4102073204.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a/0


array([[inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf]])

In [107]:
a/2

array([[ 2. ,  2.5,  3. ,  3.5,  4. ,  4.5],
       [ 5. ,  5.5,  6. ,  6.5,  7. ,  7.5],
       [ 8. ,  8.5,  9. ,  9.5, 10. , 10.5],
       [11. , 11.5, 12. , 12.5, 13. , 13.5],
       [14. , 14.5, 15. , 15.5, 16. , 16.5],
       [17. , 17.5, 18. , 18.5, 19. , 19.5]])

In [108]:
a**2

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]], dtype=int32)

In [113]:
a**3

array([[   64,   125,   216,   343,   512,   729],
       [ 1000,  1331,  1728,  2197,  2744,  3375],
       [ 4096,  4913,  5832,  6859,  8000,  9261],
       [10648, 12167, 13824, 15625, 17576, 19683],
       [21952, 24389, 27000, 29791, 32768, 35937],
       [39304, 42875, 46656, 50653, 54872, 59319]], dtype=int32)

In [114]:
pow(a,3)

array([[   64,   125,   216,   343,   512,   729],
       [ 1000,  1331,  1728,  2197,  2744,  3375],
       [ 4096,  4913,  5832,  6859,  8000,  9261],
       [10648, 12167, 13824, 15625, 17576, 19683],
       [21952, 24389, 27000, 29791, 32768, 35937],
       [39304, 42875, 46656, 50653, 54872, 59319]], dtype=int32)

In [115]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [144]:
b = [2,3,1,2,3,2]

In [145]:
b = np.array(b)

In [131]:
a+b

array([[ 6,  8,  7,  9, 11, 11],
       [12, 14, 13, 15, 17, 17],
       [18, 20, 19, 21, 23, 23],
       [24, 26, 25, 27, 29, 29],
       [30, 32, 31, 33, 35, 35],
       [36, 38, 37, 39, 41, 41]])

In [138]:
b = [[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]]

In [139]:
b = np.array(b)

In [140]:
a+b

array([[ 8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40, 42],
       [44, 46, 48, 50, 52, 54],
       [56, 58, 60, 62, 64, 66],
       [68, 70, 72, 74, 76, 78]])

In [141]:
b = b.T

In [142]:
b

array([[ 4, 10, 16, 22, 28, 34],
       [ 5, 11, 17, 23, 29, 35],
       [ 6, 12, 18, 24, 30, 36],
       [ 7, 13, 19, 25, 31, 37],
       [ 8, 14, 20, 26, 32, 38],
       [ 9, 15, 21, 27, 33, 39]])

In [143]:
a+b

array([[ 8, 15, 22, 29, 36, 43],
       [15, 22, 29, 36, 43, 50],
       [22, 29, 36, 43, 50, 57],
       [29, 36, 43, 50, 57, 64],
       [36, 43, 50, 57, 64, 71],
       [43, 50, 57, 64, 71, 78]])

In [146]:
b= b.reshape(1,-1)

In [147]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [148]:
b

array([[2, 3, 1, 2, 3, 2]])

In [149]:
b.T

array([[2],
       [3],
       [1],
       [2],
       [3],
       [2]])

In [150]:
a+b.T

array([[ 6,  7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17, 18],
       [17, 18, 19, 20, 21, 22],
       [24, 25, 26, 27, 28, 29],
       [31, 32, 33, 34, 35, 36],
       [36, 37, 38, 39, 40, 41]])

In [152]:
np.sqrt(a)

array([[2.        , 2.23606798, 2.44948974, 2.64575131, 2.82842712,
        3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
        3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
        4.58257569],
       [4.69041576, 4.79583152, 4.89897949, 5.        , 5.09901951,
        5.19615242],
       [5.29150262, 5.38516481, 5.47722558, 5.56776436, 5.65685425,
        5.74456265],
       [5.83095189, 5.91607978, 6.        , 6.08276253, 6.164414  ,
        6.244998  ]])

In [153]:
np.exp(a)

array([[5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
        2.98095799e+03, 8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06, 3.26901737e+06],
       [8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
        4.85165195e+08, 1.31881573e+09],
       [3.58491285e+09, 9.74480345e+09, 2.64891221e+10, 7.20048993e+10,
        1.95729609e+11, 5.32048241e+11],
       [1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13,
        7.89629602e+13, 2.14643580e+14],
       [5.83461743e+14, 1.58601345e+15, 4.31123155e+15, 1.17191424e+16,
        3.18559318e+16, 8.65934004e+16]])

In [154]:
np.log(a)

array([[1.38629436, 1.60943791, 1.79175947, 1.94591015, 2.07944154,
        2.19722458],
       [2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
        2.7080502 ],
       [2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
        3.04452244],
       [3.09104245, 3.13549422, 3.17805383, 3.21887582, 3.25809654,
        3.29583687],
       [3.33220451, 3.36729583, 3.40119738, 3.4339872 , 3.4657359 ,
        3.49650756],
       [3.52636052, 3.55534806, 3.58351894, 3.61091791, 3.63758616,
        3.66356165]])

In [156]:
np.log10(a)

array([[0.60205999, 0.69897   , 0.77815125, 0.84509804, 0.90308999,
        0.95424251],
       [1.        , 1.04139269, 1.07918125, 1.11394335, 1.14612804,
        1.17609126],
       [1.20411998, 1.23044892, 1.25527251, 1.2787536 , 1.30103   ,
        1.32221929],
       [1.34242268, 1.36172784, 1.38021124, 1.39794001, 1.41497335,
        1.43136376],
       [1.44715803, 1.462398  , 1.47712125, 1.49136169, 1.50514998,
        1.51851394],
       [1.53147892, 1.54406804, 1.5563025 , 1.56820172, 1.5797836 ,
        1.59106461]])

In [157]:
x= np.array([1,2,3])

In [185]:
# Shallow Copy
y = x

In [159]:
y

array([1, 2, 3])

In [161]:
# Deep Copy
z = np.copy(x)

In [162]:
z

array([1, 2, 3])

In [163]:
x[0] = 100

In [167]:
x

array([100,   2,   3])

In [164]:
y

array([100,   2,   3])

In [165]:
z

array([1, 2, 3])

In [186]:
id(x)

2511735896848

In [187]:
id(y)

2511735896848

In [188]:
id(z)

2511731371824

In [190]:
id(x[0])

2511738249136

In [192]:
id(y[0])

2511730327856

In [193]:
su = np.array([567, 345])

In [194]:
df = su

In [195]:
id(su)

2511733695280

In [196]:
id(df)

2511733695280

In [197]:
id(su[0])

2511730327920

In [199]:
id(df[0])

2511730329200

In [200]:
id(su[1])

2511730329264

In [201]:
id(df[1])

2511730329584

In [203]:
id(su[1]) ==id(df[1])

True

In [204]:
id(su[1]) ==id(df[0])

True

In [207]:
id(su[1]) ==id(z)

False

In [228]:
a = np.arange(4,29).reshape(5,5)

In [229]:
a

array([[ 4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28]])

In [230]:
b = np.array([1,1,2,2,3])

In [231]:
a+b

array([[ 5,  6,  8,  9, 11],
       [10, 11, 13, 14, 16],
       [15, 16, 18, 19, 21],
       [20, 21, 23, 24, 26],
       [25, 26, 28, 29, 31]])

In [232]:
b = b.T

In [233]:
a+b

array([[ 5,  6,  8,  9, 11],
       [10, 11, 13, 14, 16],
       [15, 16, 18, 19, 21],
       [20, 21, 23, 24, 26],
       [25, 26, 28, 29, 31]])

In [234]:
b

array([1, 1, 2, 2, 3])

In [235]:
b.T

array([1, 1, 2, 2, 3])

In [236]:
b = b.reshape(-1,1)

In [237]:
b

array([[1],
       [1],
       [2],
       [2],
       [3]])

In [238]:
a+b

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [27, 28, 29, 30, 31]])